create table if not exists public.agent_responses (
    id bigint generated by default as identity primary key,
    query text not null,
    query_key text not null,
    response text not null,
    model text not null,
    created_at timestamptz not null default now()
);

create index if not exists agent_responses_query_key_created_at_idx
on public.agent_responses (query_key, created_at desc);

alter table public.agent_responses enable row level security;